// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHF_jSYaZtt37eisPFIXOTvBtdOUuZUag',
    appId: '1:556284932857:web:78e2a46dd1395f9699e828',
    messagingSenderId: '556284932857',
    projectId: 'fidenz-quiz-app',
    authDomain: 'fidenz-quiz-app.firebaseapp.com',
    storageBucket: 'fidenz-quiz-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD66Tfxs2eSCwzNewZrcviB-mxOrTANCwE',
    appId: '1:556284932857:android:eba6c54dd539f0a799e828',
    messagingSenderId: '556284932857',
    projectId: 'fidenz-quiz-app',
    storageBucket: 'fidenz-quiz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWVz5Tp_u1HoXtQpLa_-HdCNejhl1HmA',
    appId: '1:556284932857:ios:f46f8843ccc241fa99e828',
    messagingSenderId: '556284932857',
    projectId: 'fidenz-quiz-app',
    storageBucket: 'fidenz-quiz-app.appspot.com',
    iosBundleId: 'com.example.quizGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlWVz5Tp_u1HoXtQpLa_-HdCNejhl1HmA',
    appId: '1:556284932857:ios:9927d68413c81cc299e828',
    messagingSenderId: '556284932857',
    projectId: 'fidenz-quiz-app',
    storageBucket: 'fidenz-quiz-app.appspot.com',
    iosBundleId: 'com.example.quizGame.RunnerTests',
  );
}
